CREATE TABLE `sms_log_2017_16` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` bigint(20) NOT NULL,
  `task_type` int(11) DEFAULT '1' COMMENT '任务类型',
  `point` int(11) NOT NULL DEFAULT '0' COMMENT '消费积分',
  `phone_no` varchar(15) NOT NULL COMMENT '手机号',
  `user_id` int(20) NOT NULL COMMENT '用户ID',
  `status` int(1) DEFAULT '1' COMMENT '状态 ：1,成功 2,失败',
  `client_id` int(11) DEFAULT NULL COMMENT '发送客户端ID',
  `receive_code` int(11) DEFAULT '-1' COMMENT '抵达状态-1：接收中 0：已到达 1:空号 2：关机停机 3：发送频率过高 4：签名无效 5：黑词 6：黑名单 7：短信内容有误 99：其他 ',
  `receive_time` int(11) DEFAULT NULL COMMENT '抵达时间',
  `receive_desc` varchar(32) DEFAULT NULL COMMENT '抵达状态说明',
  `service_code` varchar(32) DEFAULT NULL COMMENT '服务号码',
  `synchronized` int(11) DEFAULT '0' COMMENT '同步短信状态，0：不可用 1：待同步 2：已同步',
  `create_time` int(11) DEFAULT NULL,
  `fee_count` int(11) DEFAULT '1' COMMENT '计费条数',
  `msg` varchar(1024) DEFAULT NULL COMMENT '短信内容',
  `desc` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`) USING BTREE,
  KEY `create_time` (`user_id`,`create_time`) USING BTREE,
  KEY `task_id` (`task_id`,`phone_no`) USING BTREE,
  KEY `userid` (`user_id`,`synchronized`,`task_type`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=202 DEFAULT CHARSET=utf8 COMMENT='短信发送日志';
