UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="adl_msg_content_input";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_received_log";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_template_dim";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_template_ft";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_template_info_dim";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_signature_info_dim";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_received_join_log";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_sender_info_agg";
UPDATE config_taregt_log 
SET is_chack=1
WHERE task_name="idl_msg_receiver_info_agg";